services:
  # db:
  #   image: public.ecr.aws/docker/library/postgres:16-alpine
  #   container_name: solar-db
  #   environment:
  #     POSTGRES_DB: solar
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d solar"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20

  # app:
  #   build: .
  #   container_name: solar-app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/solar
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  #     SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
  #   ports:
  #     - "8088:8080"

  front:
    build:
      context: ../mobile
      #args:
      #  - NEXT_PUBLIC_API_URL=http://192.168.100.28:8088
    container_name: solar-front
    ports:
      - "8001:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.solar-mate-front.rule=Host(`mate.solaryazd.com`)
      - traefik.http.routers.solar-mate-front.tls=true
      - traefik.docker.network=traefik
      - traefik.http.routers.solar-mate-front.entrypoints=web,websecure
      - traefik.http.routers.solar-mate-front.tls.certresolver=mydnschallenge
      - traefik.http.middlewares.solar-mate-front.headers.SSLRedirect=true
      - traefik.http.middlewares.solar-mate-front.headers.STSSeconds=315360000
      - traefik.http.middlewares.solar-mate-front.headers.browserXSSFilter=true
      - traefik.http.middlewares.solar-mate-front.headers.contentTypeNosniff=true
      - traefik.http.middlewares.solar-mate-front.headers.forceSTSHeader=true
     # - traefik.http.middlewares.solar-mate-front.headers.SSLHost=finitx.com
      - traefik.http.middlewares.solar-mate-front.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.solar-mate-front.headers.STSPreload=true
      - traefik.http.routers.solar-mate-front.middlewares=portainer@docker
      - traefik.http.services.solar-mate-front.loadbalancer.server.port=80
      - "traefik.http.routers.portainer.observability.tracing=true"  
    #environment:
     # - NEXT_PUBLIC_API_URL=http://192.168.100.28:8088
   # depends_on:
     # - app

#volumes:
#  pgdata:
