services:
  db:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: solar-db
    environment:
      POSTGRES_DB: solar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d solar"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: solar-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/solar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
    ports:
      - "8088:8080"

  front:
    build:
      context: ../web
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.100.28:8088
    container_name: solar-front
    ports:
      - "3100:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.100.28:8088
    depends_on:
      - app

volumes:
  pgdata:
